name: Verify input string
<<<<<<< HEAD
description: This action verifies if the input string is of valid format
runs:
  using: composite
  steps:
    - name: Checkout the repository
=======
description: This action verifies if the input string is of valid format for parallel deployment in all regions.

runs:
  using: composite
  steps:
    - name: Checkout repository
>>>>>>> origin/dev
      uses: actions/checkout@v4

    - name: Get the event name
      shell: bash
      run: |
        echo "Event name: ${{ github.event_name }}"
<<<<<<< HEAD
        
    - name: Get PR title in a Pull request event
      if: ${{ github.event_name == 'pull_request_review' }}
      uses: ./.github/actions/get-pr-title

    - name: Get PR title in a Pull request event
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/actions/get-pr-title
  
    - name: Get commit message in a Push to branch event
      if: ${{ github.event_name == 'push' }}
      uses: ./.github/actions/get-branch-commit


    - name: Verify Input string Format
=======
      
    - name: Get PR title in a Pull request review event
      if: ${{ github.event_name == 'pull_request_review' }}
      uses: ./.github/actions/pr-title

    - name: Get PR title in a Pull request event
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/actions/gpr-title      

  

    - name: Check existence of preprod and prod strings in the PR title
      shell: bash
      run: |
        inputstring="${{ env.INPUT_STRING }}"
        echo $inputstring
        echo ${{ github.event.pull_request.base.ref }}
        if [[ ${{ github.event.pull_request.base.ref }} == 'preproduction' ]]; then
          if [[ "$inputstring" =~ 'preprod' || "$inputstring" =~ 'Preprod' ]]; then                    
            echo "$inputstring is valid for preprod deployment."
          else
            echo "$inputstring is not valid for preprod deployment as it doesnot contains 'preprod/Preprod' in PR title."
            exit 1
          fi  
        fi
        if [[ ${{ github.event.pull_request.base.ref }} == 'production' ]]; then
          if [[ "$inputstring" =~ 'prod' || "$inputstring" =~ 'Prod' ]]; then                    
            echo "$inputstring is valid for prod deployment."
          else
            echo "$inputstring is not valid for prod deployment as it doesnot contains 'prod/Prod' in PR title."
            exit 1
          fi 
        fi
    - name: Verify Input string
>>>>>>> origin/dev
      shell: bash
      run: |
        inputstring="${{ env.INPUT_STRING }}"
        switch=0
        echo $inputstring
<<<<<<< HEAD
        if [[ $inputstring =~ ^\[[a-zA-Z]+\/[a-zA-Z]+\/[a-zA-Z]+\/[a-zA-Z]+\]:( [a-zA-Z0-9]+)* ]]; then 
          switch=0
=======
        if [[ $inputstring =~ ^\[[a-zA-Z]+\/[a-zA-Z]+\/[a-zA-Z]+\]:( [a-zA-Z0-9]+)* ]]; then
>>>>>>> origin/dev
          echo "$inputstring matches the required format."
          ap_region=$(echo $inputstring | cut -d "]" -f1 | sed 's/^\[//' | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')
          eu_region=$(echo $inputstring | cut -d "]" -f1 | sed 's/^\[//' | cut -d/ -f2 | tr '[:upper:]' '[:lower:]')
          us_region=$(echo $inputstring | cut -d "]" -f1 | sed 's/^\[//' | cut -d/ -f3 | tr '[:upper:]' '[:lower:]')
<<<<<<< HEAD
          subgraph_name=$(echo $inputstring | cut -d "]" -f1 | sed 's/^\[//' | cut -d/ -f4 | tr '[:upper:]' '[:lower:]')
          # tag=$(echo $inputstring | cut -d "]" -f1 | sed 's/^\[//' | cut -d/ -f5 | tr '[:upper:]' '[:lower:]')
          echo $ap_region
          echo $eu_region
          echo $us_region
          echo $subgraph_name
          # echo $tag
          if [[ $us_region == 'us' || $eu_region == 'eu' || $ap_region == 'ap' ]]; then
            echo "$region is valid and is present in one of us, eu, ap."
          else
            switch=1
            echo "$region is not valid. Please use region in one of us, eu, ap."
          fi
          if [[ $subgraph_name == 'recommendationgraph' ]]; then
            echo "$subgraph_name is a valid Subgraph name."
          else
            switch=1
            echo "$subgraph_name is not a valid Subgraph name. Please use correct Subgraph name"
          fi
    
          if [[ $switch == 1 ]]; then
            exit 1
          fi
=======
          echo $ap_region
          echo $eu_region
          echo $us_region

          if [[ $us_region == 'us' ]]; then                    
            echo "$us_region is valid and is present in one of us, eu, ap."
          else
            echo "$us_region is not valid. Please use one of the allowed region us, eu, ap."
            exit 1
          fi  

          if [[ $eu_region == 'eu' ]]; then                    
            echo "$eu_region is valid and is present in one of us, eu, ap."
          else
            echo "$eu_region is not valid. Please use one of the allowed region us, eu, ap."
            exit 1
          fi

          if [[ $ap_region == 'ap' ]]; then                    
            echo "$ap_region is valid and is present in one of us, eu, ap."          
          else
            echo "$ap_region is not valid. Please use one of the allowed region us, eu, ap."
            exit 1
          fi

>>>>>>> origin/dev
        else
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo 'PR title is not of correct format. Please update PR title.'
          elif [[ ${{ github.event_name }} == 'push' ]]; then
            echo 'Commit message is not of correct format. Please recommit and push.'
          fi
          exit 1
        fi
