### Deployment Information

**Dev Environment:**
- AP Region: `Dev: <image-tag>`
- EU Region: `Dev: <image-tag>`
- US Region: `Dev: <image-tag>`

**Staging Environment:**
- AP Region: `Staging: <image-tag>`
- EU Region: `Staging: <image-tag>`
- US Region: `Staging: <image-tag>`

**Prod Environment:**
- AP Region: `Prod: <image-tag>`
- EU Region: `Prod: <image-tag>`
- US Region: `Prod: <image-tag>`


