name: Build and Push Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t lakshmi979/my-app:$GITHUB_SHA .

      - name: List Docker images (for debugging)
        run: |
          docker images

      - name: Push Docker image to Docker Hub
        run: |
          docker push lakshmi979/my-app:$GITHUB_SHA

  extract-pr-info:
    #needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR information
        run: |
          PR_BODY=$(cat <<EOF
          # Select Environment
            - Dev: `N`
            - Staging: `N`
            - Preprod: `N`
            - Prod: `N`

          # Image Tags for Selected Environment

          ### Dev Environment
            - **AP Region:** `drtef`
            - **EU Region:** `fdger`
            - **US Region:** `ertre`

          ### Staging Environment
            - **AP Region:** ``
            - **EU Region:** ``
            - **US Region:** ``

          ### Preprod Environment
            - **AP Region:** ``
            - **EU Region:** ``
            - **US Region:** ``

          ### Prod Environment
            - **AP Region:** ``
            - **EU Region:** ``
            - **US Region:** ``
          EOF
          )

          # Extract image tags from the PR description
          IMAGE_TAG_DEV_AP=$(echo "$PR_BODY" | grep -oP '(?<=Dev Environment\s*- AP Region: `)[^`]+')
          IMAGE_TAG_DEV_EU=$(echo "$PR_BODY" | grep -oP '(?<=Dev Environment\s*- EU Region: `)[^`]+')
          IMAGE_TAG_DEV_US=$(echo "$PR_BODY" | grep -oP '(?<=Dev Environment\s*- US Region: `)[^`]+')

          IMAGE_TAG_STAGING_AP=$(echo "$PR_BODY" | grep -oP '(?<=Staging Environment\s*- AP Region: `)[^`]+')
          IMAGE_TAG_STAGING_EU=$(echo "$PR_BODY" | grep -oP '(?<=Staging Environment\s*- EU Region: `)[^`]+')
          IMAGE_TAG_STAGING_US=$(echo "$PR_BODY" | grep -oP '(?<=Staging Environment\s*- US Region: `)[^`]+')

          IMAGE_TAG_PROD_AP=$(echo "$PR_BODY" | grep -oP '(?<=Prod Environment\s*- AP Region: `)[^`]+')
          IMAGE_TAG_PROD_EU=$(echo "$PR_BODY" | grep -oP '(?<=Prod Environment\s*- EU Region: `)[^`]+')
          IMAGE_TAG_PROD_US=$(echo "$PR_BODY" | grep -oP '(?<=Prod Environment\s*- US Region: `)[^`]+')

          # Save tags to GitHub environment variables
          echo "IMAGE_TAG_DEV_AP=$IMAGE_TAG_DEV_AP" >> $GITHUB_ENV
          echo "IMAGE_TAG_DEV_EU=$IMAGE_TAG_DEV_EU" >> $GITHUB_ENV
          echo "IMAGE_TAG_DEV_US=$IMAGE_TAG_DEV_US" >> $GITHUB_ENV
          echo "IMAGE_TAG_STAGING_AP=$IMAGE_TAG_STAGING_AP" >> $GITHUB_ENV
          echo "IMAGE_TAG_STAGING_EU=$IMAGE_TAG_STAGING_EU" >> $GITHUB_ENV
          echo "IMAGE_TAG_STAGING_US=$IMAGE_TAG_STAGING_US" >> $GITHUB_ENV
          echo "IMAGE_TAG_PROD_AP=$IMAGE_TAG_PROD_AP" >> $GITHUB_ENV
          echo "IMAGE_TAG_PROD_EU=$IMAGE_TAG_PROD_EU" >> $GITHUB_ENV
          echo "IMAGE_TAG_PROD_US=$IMAGE_TAG_PROD_US" >> $GITHUB_ENV

      - name: Print Image Tags
        run: |
          echo "Dev AP: $IMAGE_TAG_DEV_AP"
          echo "Dev EU: $IMAGE_TAG_DEV_EU"
          echo "Dev US: $IMAGE_TAG_DEV_US"
          echo "Staging AP: $IMAGE_TAG_STAGING_AP"
          echo "Staging EU: $IMAGE_TAG_STAGING_EU"
          echo "Staging US: $IMAGE_TAG_STAGING_US"
          echo "Prod AP: $IMAGE_TAG_PROD_AP"
          echo "Prod EU: $IMAGE_TAG_PROD_EU"
          echo "Prod US: $IMAGE_TAG_PROD_US"
