name: Build and Deploy Docker Image to Docker Hub
on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t your-docker-LAKSHMIKALA77/my-app:$GITHUB_SHA .

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-docker-LAKSHMIKALA77/my-app:$GITHUB_SHA
