name: Deploy to Dev - eu Region

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev-eu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract image tag for Dev eu
        run: |
          # Extract the image tag from the PR description
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # Search for the 'Dev' image tag in the PR description (assuming it's like 'Dev: <image-tag>')
          IMAGE_TAG_DEV_EU=$(echo "$PR_BODY" | grep -oP '(?<=Dev: )[^\n]+' | xargs)

          # Sanitize the image tag (remove any quotes)
          IMAGE_TAG_DEV_EU=$(echo "$IMAGE_TAG_DEV_eu" | sed 's/["]//g')

          # Check if the tag is found and output it
          if [[ -z "$IMAGE_TAG_DEV_EU" ]]; then
            echo "Error: Dev image tag not found!"
            exit 1
          fi

          echo "Dev eu Image Tag: $IMAGE_TAG_DEV_eu"
          echo "IMAGE_TAG_DEV_eu=$IMAGE_TAG_DEV_eu" >> $GITHUB_ENV

      - name: Deploy to Dev - eu
        run: |
          echo "Deploying to Dev eu Region with Image Tag: $IMAGE_TAG_DEV_EU"
          # Add your deployment command here, e.g., kubectl, docker, etc.
