# name: Deploy to Preprod - Single Region

# on:
#   pull_request:
#     branches:
#       - preprod

# jobs:
#   deploy-single-region:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Determine Target Region
#         id: determine-region
#         run: |
#           PR_TITLE="${{ github.event.pull_request.title }}"
#           echo "PR Title: $PR_TITLE"

#           if [[ "$PR_TITLE" == *"[ap]: deploy"* ]]; then
#             echo "TARGET_REGION=AP" >> $GITHUB_ENV
#           elif [[ "$PR_TITLE" == *"[eu]: deploy"* ]]; then
#             echo "TARGET_REGION=EU" >> $GITHUB_ENV
#           elif [[ "$PR_TITLE" == *"[us]: deploy"* ]]; then
#             echo "TARGET_REGION=US" >> $GITHUB_ENV
#           else
#             echo "TARGET_REGION=ALL" >> $GITHUB_ENV

#       - name: Build Docker Image
#         run: |
#           docker build \
#             --build-arg REGION=${{ env.TARGET_REGION }} \
#             -t lakshmi979/my-app:$GITHUB_SHA .

#       
name: Trigger Preprod Region Deployment

on:
  pull_request:
    branches:
      - preprod

jobs:
  determine-region:
    runs-on: ubuntu-latest
    outputs:
      target-file: ${{ steps.set-region.outputs.target-file }}
    steps:
      - name: Parse PR Title
        id: set-region
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          if [[ "$PR_TITLE" == *"[ap]"* ]]; then
            echo "target-file=preprod-ap.yaml" >> $GITHUB_ENV
            echo "::set-output name=target-file::preprod-ap.yaml"
          elif [[ "$PR_TITLE" == *"[eu]"* ]]; then
            echo "target-file=preprod-eu.yaml" >> $GITHUB_ENV
            echo "::set-output name=target-file::preprod-eu.yaml"
          elif [[ "$PR_TITLE" == *"[us]"* ]]; then
            echo "target-file=preprod-us.yaml" >> $GITHUB_ENV
            echo "::set-output name=target-file::preprod-us.yaml"
          else
            echo "Error: No valid region specified in PR title."
            exit 1
          fi

  trigger-region-deployment:
    needs: determine-region
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Region Deployment
        uses: actions/checkout@v2

      - name: Call Deployment File
        run: |
          echo "Triggering deployment using ${{ needs.determine-region.outputs.target-file }}"
        # Replace the following with actual logic to trigger the region-specific file
        # For example, this could run a script or call a reusable workflow
        run: |
          ./scripts/${{ needs.determine-region.outputs.target-file }}

