name: Deploy to Preprod - Single Region

on:
  pull_request:
    branches:
      - preprod

jobs:
  deploy-single-region:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Determine the target region based on PR title
      - name: Determine Target Region
        id: determine-region
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          if [[ "$PR_TITLE" == *"[ap]: deploy"* ]]; then
            echo "TARGET_REGION=AP" >> $GITHUB_ENV
          elif [[ "$PR_TITLE" == *"[eu]: deploy"* ]]; then
            echo "TARGET_REGION=EU" >> $GITHUB_ENV
          elif [[ "$PR_TITLE" == *"[us]: deploy"* ]]; then
            echo "TARGET_REGION=US" >> $GITHUB_ENV
          else
            echo "TARGET_REGION=ALL" >> $GITHUB_ENV
          fi

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg REGION=${{ env.TARGET_REGION }} \
            -t lakshmi979/my-app:$GITHUB_SHA .

      # Step 5: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push lakshmi979/my-app:$GITHUB_SHA

      # Step 6: Validate and Deploy to Preprod
      - name: Deploy to Preprod
        run: |
          if [[ "${{ env.TARGET_REGION }}" == "ALL" ]]; then
            echo "Deploying to all preprod regions (AP, EU, US)"
          else
            echo "Deploying to preprod ${{ env.TARGET_REGION }} region"
          fi
