name: Build and Push Docker Image to Docker Hub
on:
  pull_request:
    branches:
       - prod

jobs:
  lint:
    if: ${{ startsWith(github.event.pull_request.title, '[ap/') }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build-and-push:
    needs: lint
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t lakshmi979/my-app:$GITHUB_SHA .

      - name: List Docker images (for debugging)
        run: |
          docker images

      - name: Push Docker image to Docker Hub
        run: |
          docker push lakshmi979/my-app:$GITHUB_SHA

      - name: Parse and Validate PR Body
        id: parse_pr
        run: |
          # Read the pull request body
          PR_BODY=$(jq -r '.pull_request.body' < "$GITHUB_EVENT_PATH")
          echo "PR_BODY=$PR_BODY"

          # Extract selected environments
          PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)[^`]+')

          # Echo selected environment for later steps
          echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV

          # Extract image tags for PROD
          PROD_IMAGE_AP=$(echo "$PR_BODY" | grep -A 3 "Prod Environment" | grep "AP Region:" | awk -F'`' '{print $2}' | tr -d '[:space:]')
          echo "PROD_IMAGE_AP=$PROD_IMAGE_AP" >> $GITHUB_ENV

      - name: Validate and Display Selected Environments
        run: |
          echo "Selected Environments:"

          if [ "$PROD_SELECTED" == "Y" ]; then
            if [ -z "$PROD_IMAGE_AP" ]; then
              echo "Error: Missing image tag values for Prod Environment."
              exit 1
            fi
            echo "Prod: AP=$PROD_IMAGE_AP"
          fi
