name: Deploy to Docker Hub

on:
  pull_request:
    branches:
      - dev  # Trigger this workflow on PR to dev branch

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform support, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image to Docker Hub
        run: |
          # Build the Docker image with the tag provided in the PR description (e.g., my-app:tag)
          docker build -t myusername/my-app:$IMAGE_TAG .
          docker push myusername/my-app:$IMAGE_TAG
